apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: zyxue/model-with-metrics:0.3-rc.1
          name: classifier
    graph:
      children: []
      name: classifier
      type: MODEL
    name: example
    replicas: 1
